#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: The Panic Room

# Short bio or description (displayed in the header)
description: En The Panic Room hacemos posible la integración del hardware y software para mejorar la experiencia del usuario basándonos en las tendencias tecnológicas.
short_description: Full stack developers

authors:
  - Valentina Azócar
  - Jhonny Mata
  - Jesús Marín
  - Jesús Rodríguez
  - Carlos Gamardo

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-147132627-1

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  sass_dir: _sass

sitemap: true

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME